### PR TITLE
Add the ability to change choose backoff strategies

### PR DESCRIPTION
**Pull request by liambuchanan**
Hey, not sure if this is how you would've done it or even a feature you want but it's something I would've used recently if it existed. lmk what you think. I would've liked to add the ability to take a user supplied backoff strategy fn but I timeboxed my work on this pretty aggressively

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Thanks for this, I think it would be a nice addition to add these strategies. 

I wonder what the best pubic API for these is? Perhaps these should be names functions which can be imported directly?

```
import exponentialBackoff from 'ember-backoff/exponential-backoff';
import linearBackoff from 'ember-backoff/linear-backoff';
```

What do you think?

Also, before we merge, I think it would be useful to add tests for the various test strategies.

**Comment by liambuchanan** [comment]
Agree with all of the above :)

I think rather than the string arg I've got it'd be more sensible to have a user supply a strategy function if they want anything other than exponential backoff and supply users with some strategies they can import as you've suggested.

**Comment by liambuchanan** [comment]
Sorry about the delay here. Thought I would get to it over the weekend. Hopefully some time this week.

**Comment by liambuchanan** [comment]
Just added custom strategies that take `initialWait` and `retryCount` params. I considered simplifying the api to retryWithBackoff to take a polymorphic `backoff` param in place of both the `initialWaitMilliseconds` and custom strategy param that could either be: left unset, a number that would become `initialWaitMilliseconds` passed to the exponential strategy, or a custom strategy function which would just take a `retryCount` param but decided against overloading types.

**Comment by GavinJoyce** [comment]
> ...but decided against overloading types

👍 

Thanks for this, it's a nice improvement to the addon. Perhaps you might add some examples to the readme (and a bonus to the dummy app)?

**Comment by liambuchanan** [comment]
sure. Let me know what you think of this

**Comment by GavinJoyce** [comment]
Nice, thanks. As a final step, perhaps you might squash down to a single commit before I merge? Thanks

**Comment by GavinJoyce** [comment]
Thanks 🍻

**Pull request merged**
